function importAll(r) {
    let images = {};
    r.keys().map((item) => { images[item.replace('./', '')] = r(item); });
    return images;
  }
  
  const images = importAll(require.context('../assets/img', false, /\.(png|jpe?g|svg)$/));
  
 
export const ProductsData=[
  {
    id: 1,
    title: "Green Leaf Lettuce",
    unit: "each",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 14,
    oldPrice: 0,
    sales: 0,
    sku: "F001",
    stock: 6,
    images: [{id:1,small:images['product-1.png']},{id:2,medium:images['Green-Leaf-Lettuce-each-2x.png']}],
    category: "Fresh Vegetable",
    href: "green-leaf-lettuce",
    tag: [
      { id: 1, name: "lettuce" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 2,
    title: "Rainbow Chard",
    unit: "1lb",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4FD",
    stock: 0,
    images: [{id:1,small:images['product-2.png']},{id:2,medium:images['Rainbow-Chard-Package-per-lb-2x.png']}],
    category: "Fresh Vegetable",
    href:"rainbow-chard",
    tag: [
      { id: 1, name: "rainbow-chard" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 3,
    title: "Clementine",
    unit: "5ct",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 13,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4FC",
    stock: 0,
    images: [{id:1,small:images['product-3.png']},{id:2,medium:images['Clementine-5ct-2x.png']}],
    category: "Fresh Fruits",
    href:"clementine",
    tag: [
      { id: 1, name: "clementine" },
      { id: 2, name: "fresh fruits" },
    ],
  },
  {
    id: 4,
    title: "Rainbow Peppers",
    unit: "4ct",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4FA",
    stock: 52,
    images: [{id:1,small:images['product-4.png']},{id:2,medium:images['Rainbow-Peppers-4ct-2x.png']}],
    category: "Fresh Vegetable",
    href: "rainbow-peppers",
    tag: [
      { id: 1, name: "rainbow-peppers" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 5,
    title: "Blueberry",
    unit: "25qt",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 13,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F9",
    stock: 99,
    images: [{id:1,small:images['product-5.png']},{id:2,medium:images['Blackberries-1-25-qt-2x.png']}],
    category: "Fresh Fruits",
    href:"blueberry",
    tag: [
      { id: 1, name: "blueberries" },
      { id: 2, name: "fresh fruits" },
    ],
  },
  {
    id: 6,
    title: "Calabaza Squash",
    unit: "each",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F8",
    stock: 59,
    images: [{id:1,small:images['product-6.png']},{id:2,medium:images['Calabaza-Squash-Package-each-2x.png']}],
    category: "Fresh Vegetable",
    href: "calabazasquash",
    tag: [
      { id: 1, name: "calabaza-squash" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 7,
    title: "Lettuce",
    unit: "1lb",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 14,
    oldPrice: 0,
    sales: 0,
    sku: " 9AF4F7",
    stock: 103,
    images: [{id:1,small:images['product-7.png']},{id:2,medium:images['Lettuce-1lb-2x.png']}],
    category: "Fresh Vegetable",
    href: "lettuce",
    tag: [
      { id: 1, name: "lettuce" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 8,
    title: "Radicchio",
    unit: "12ct",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "F0056",
    stock: 0,
    images: [{id:1,small:images['product-8.png']},{id:2,medium:images['Radicchio-12ct-2x.png']}],
    category: "Fresh Vegetable",
    href: "radicchio",
    tag: [
      { id: 1, name: "radicchio" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 9,
    title: "Parsley",
    unit: "each",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F5",
    stock: 97,
    images: [{id:1,small:images['product-9.png']},{id:2,medium:images['Parsley-each-2x.png']}],
    category: "Fresh Vegetable",
    href: "parsley",
    tag: [
      { id: 1, name: "parsley" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 10,
    title: "Strawberrie",
    unit: "25oz",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 13,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F4",
    stock: 47,
    images: [{id:1,small:images['product-10.png']},{id:2,medium:images['Strawberries-9-25oz-2x.png']}],
    category: "Fresh Fruits",
    href: "strawberrie",
    tag: [
      { id: 1, name: "strawberries" },
      { id: 2, name: "fresh fruits" },
    ],
  },
  {
    id: 11,
    title: "Cauliflower",
    unit: "35lb",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F3",
    stock: 90,
    images: [{id:1,small:images['product-11.png']},{id:2,medium:images['Cauliflower-1-35lb-2x.png']}],
    category: "Fresh Vegetable",
    href: "cauliflower",
    tag: [
      { id: 1, name: "cauliflower" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 12,
    title: "Organic Purple Cauliflower",
    unit: "1lb",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 11,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F2",
    stock: 90,
    images: [{id:1,small:images['product-12.png']},{id:2,medium:images['Organic-Purple-Cauliflower-1lb-2x.png']}],
    category: "Fresh Vegetable",
    href: "organic-purple-cauliflower",
    tag: [
      { id: 1, name: "cauliflower" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 13,
    title: "Ahold Acorn Squash",
    unit: "1ct",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F1",
    stock: 0,
    images: [{id:1,small:images['product-13.png']},{id:2,medium:images['Ahold-Acorn-Squash-1ct-2x.png']}],
    category: "Fresh Vegetable",
    href: "ahold-acorn-squash",
    tag: [
      { id: 1, name: "squash" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 14,
    title: "Bok Choy Cabbage",
    unit: "1lb",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F1",
    stock: 97,
    images: [{id:1,small:images['product-14.png']},{id:2,medium:images['Bok-Choy-Cabbage-per-lb-2x.png']}],
    category: "Fresh Vegetable",
    href: "bok-choy-cabbage",
    tag: [
      { id: 1, name: "cabbage" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 15,
    title: "Strawberries Package",
    unit: "25oz",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 14,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4EF",
    stock: 86,
    images: [{id:1,small:images['product-15.png']},{id:2,medium:images['Strawberries-Package-2-25-oz-2x.png']}],
    category: " Fresh Fruits",
    href: "strawberries-hackage",
    tag: [
      { id: 1, name: "strawberries" },
      { id: 2, name: "fresh fruits" },
    ],
  },
  {
    id: 16,
    title: "Aloe Vera Leaf",
    unit: "each",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4EE",
    stock: 65,
    images: [{id:1,small:images['product-16.png']},{id:2,medium:images['Aloe-Vera-Leaf-each-2x.png']}],
    category: "Fresh Vegetable",
    href: "aloe-vera-leaf",
    tag: [
      { id: 1, name: "aloe-vera-leaf" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 17,
    title: "Pineapple Imported",
    unit: "5lb",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4ED",
    stock: 70,
    images: [{id:1,small:images['product-17.png']},{id:2,medium:images['Pineapple-1-5lb-2x.png']}],
    category: "Fresh Fruits",
    href: "pineapple-imported",
    tag: [
      { id: 1, name: "pineapple" },
      { id: 2, name: "fresh fruits" },
    ],
  },
  {
    id: 18,
    title: "Organic Broccoli",
    unit: "10oz",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4EC",
    stock: 110,
    images: [{id:1,small:images['product-18.png']},{id:2,medium:images['Organic-Broccoli-10oz-2x.png']}],
    category: "Fresh Vegetable",
    href: "organic-broccoli",
    tag: [
      { id: 1, name: "broccoli" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  // Balık
  {
    id: 19,
    title: "Wild King Salmon Steak",
    unit: "1lb",
    description:
      "A fish is an animal which lives and breathes in water. All fish are vertebrates (have a backbone) and most breathe through gills and have fins and scales. ... There are three classes of fish: jawless, cartilaginous, and bony. All fish have a backbone.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF49E",
    stock: 110,
    images: [{id:1,small:images['product-31.png']},{id:2,medium:images['product-31-2x.png']}],
    category: "Fish",
    href: "wild-king-salmon-steak",
    tag: [
      { id: 1, name: "salmon" },
      { id: 2, name: "fish" },
    ],
  }, 
  {
    id: 20,
    title: "Canada Salmon",
    unit: "5oz",
    description:
      "A fish is an animal which lives and breathes in water. All fish are vertebrates (have a backbone) and most breathe through gills and have fins and scales. ... There are three classes of fish: jawless, cartilaginous, and bony. All fish have a backbone.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4C2",
    stock: 110,
    images: [{id:1,small:images['product-32.png']},{id:2,medium:images['product-32-2x.png']}],
    category: "Fish",
    href: "canada-salmon",
    tag: [
      { id: 1, name: "salmon" },
      { id: 2, name: "fish" },
    ],
  }, 
  {
    id: 21,
    title: "Atlantic Salmon",
    unit: "1lb",
    description:
      "A fish is an animal which lives and breathes in water. All fish are vertebrates (have a backbone) and most breathe through gills and have fins and scales. ... There are three classes of fish: jawless, cartilaginous, and bony. All fish have a backbone.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4C1",
    stock: 110,
    images: [{id:1,small:images['product-33.png']},{id:2,medium:images['product-33-2x.png']}],
    category: "Fish",
    href: "atlantic-salmon",
    tag: [
      { id: 1, name: "salmon" },
      { id: 2, name: "fish" },
    ],
  }, 
  {
    id: 22,
    title: "Salmon Filet Portion",
    unit: "6oz",
    description:
      "A fish is an animal which lives and breathes in water. All fish are vertebrates (have a backbone) and most breathe through gills and have fins and scales. ... There are three classes of fish: jawless, cartilaginous, and bony. All fish have a backbone.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF49B",
    stock: 110,
    images: [{id:1,small:images['product-34.png']},{id:2,medium:images['product-34-2x.png']}],
    category: "Fresh Seafood",
    href: "salmon-filet-portion",
    tag: [
      { id: 1, name: "salmon" },
      { id: 2, name: "fish" },
    ],
  }, 
  {
    id: 23,
    title: "Ling Cod Steak",
    unit: "1lb",
    description:
      "A fish is an animal which lives and breathes in water. All fish are vertebrates (have a backbone) and most breathe through gills and have fins and scales. ... There are three classes of fish: jawless, cartilaginous, and bony. All fish have a backbone.",
    price: 11,
    oldPrice: 0,
    sales: 0,
    sku: "9AF49A",
    stock: 110,
    images: [{id:1,small:images['product-35.png']},{id:2,medium:images['product-35-2x.png']}],
    category: "Fresh Seafood",
    href: "ling-cod-steak",
    tag: [
      { id: 1, name: "ling-cod" },
      { id: 2, name: "fish" },
    ],
  }, 
  {
    id: 24,
    title: "Peeled Deveined Shrimp",
    unit: "2lb",
    description:
      "A fish is an animal which lives and breathes in water. All fish are vertebrates (have a backbone) and most breathe through gills and have fins and scales. ... There are three classes of fish: jawless, cartilaginous, and bony. All fish have a backbone.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF499",
    stock: 110,
    images: [{id:1,small:images['product-36.png']},{id:2,medium:images['product-36-2x.png']}],
    category: "Fresh Seafood",
    href: "peeled-deveined-shrimp",
    tag: [
      { id: 1, name: "shrimp" },
      { id: 2, name: "fish" },
    ],
  }, 
  {
    id: 25,
    title: "Chilean Sea Bass",
    unit: "1lb",
    description:
      "A fish is an animal which lives and breathes in water. All fish are vertebrates (have a backbone) and most breathe through gills and have fins and scales. ... There are three classes of fish: jawless, cartilaginous, and bony. All fish have a backbone.",
    price: 14,
    oldPrice: 0,
    sales: 0,
    sku: "9AF49B",
    stock: 110,
    images: [{id:1,small:images['product-37.png']},{id:2,medium:images['product-37-2x.png']}],
    category: "Fish",
    href: "chilean-sea-bass",
    tag: [
      { id: 1, name: "sea-bass" },
      { id: 2, name: "fish" },
    ],
  }, 
  
  //meat

  {
    id: 26,
    title: "Beef Stew",
    unit: "1lb",
    description:
      "Beef, flesh of mature cattle, as distinguished from veal, the flesh of calves. The best beef is obtained from early maturing, special beef breeds. High-quality beef has firm, velvety, fine-grained lean, bright red in colour and well-marbled. The fat is smooth, creamy white, and well distributed.",
    price: 18,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4BC",
    stock: 110,
    images: [{id:1,small:images['product-38.png']},{id:2,medium:images['product-38-2x.png']}],
    category: "Meat",
    href: "beef-stew",
    tag: [
      { id: 1, name: "beef" },
      { id: 2, name: "meat" },
    ],
  }, 
  {
    id: 27,
    title: "Ground Turkey",
    unit: "1lb",
    description:
      "Beef, flesh of mature cattle, as distinguished from veal, the flesh of calves. The best beef is obtained from early maturing, special beef breeds. High-quality beef has firm, velvety, fine-grained lean, bright red in colour and well-marbled. The fat is smooth, creamy white, and well distributed.",
    price: 19,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4BB",
    stock: 110,
    images: [{id:1,small:images['product-39.png']},{id:2,medium:images['product-39-2x.png']}],
    category: "Meat",
    href: "ground-turkey",
    tag: [
      { id: 1, name: "beef" },
      { id: 2, name: "meat" },
    ],
  }, 
  {
    id: 28,
    title: "Duck Meat",
    unit: "1lb",
    description:
      "Beef, flesh of mature cattle, as distinguished from veal, the flesh of calves. The best beef is obtained from early maturing, special beef breeds. High-quality beef has firm, velvety, fine-grained lean, bright red in colour and well-marbled. The fat is smooth, creamy white, and well distributed.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4BA",
    stock: 110,
    images: [{id:1,small:images['product-40.png']},{id:2,medium:images['product-40-2x.png']}],
    category: "Meat",
    href: "duck-meat",
    tag: [
      { id: 1, name: "duck" },
      { id: 2, name: "meat" },
    ],
  }, 
  {
    id: 29,
    title: "Boneless Beef",
    unit: "1lb",
    description:
      "Beef, flesh of mature cattle, as distinguished from veal, the flesh of calves. The best beef is obtained from early maturing, special beef breeds. High-quality beef has firm, velvety, fine-grained lean, bright red in colour and well-marbled. The fat is smooth, creamy white, and well distributed.",
    price: 19,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4B9",
    stock: 110,
    images: [{id:1,small:images['product-41.png']},{id:2,medium:images['product-41-2x.png']}],
    category: "Meat",
    href: "boneless-beef",
    tag: [
      { id: 1, name: "beef" },
      { id: 2, name: "meat" },
    ],
  }, 
  {
    id: 30,
    title: "Bone In Chuck",
    unit: "1lb",
    description:
      "Beef, flesh of mature cattle, as distinguished from veal, the flesh of calves. The best beef is obtained from early maturing, special beef breeds. High-quality beef has firm, velvety, fine-grained lean, bright red in colour and well-marbled. The fat is smooth, creamy white, and well distributed.",
    price: 18,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4B8",
    stock: 110,
    images: [{id:1,small:images['product-42.png']},{id:2,medium:images['product-42-2x.png']}],
    category: "Meat",
    href: "bone-in-chuck",
    tag: [
      { id: 1, name: "beef" },
      { id: 2, name: "meat" },
    ],
  }, 
  
  //dry-fruits
  {
    id: 31,
    title: "Golden Garden Love Plum",
    unit: "220g",
    description:
      "Dried fruit is fruit from which the majority of the original water content has been removed either naturally, through sun drying, or through the use of specialized dryers or dehydrators. ... Nearly half of the dried fruits sold are raisins, followed by dates, prunes, figs, apricots, peaches, apples, and pears.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4D0",
    stock: 110,
    images: [{id:1,small:images['product-43.png']},{id:2,medium:images['product-43-2x.png']}],
    category: "Dry Fruits",
    href: "golden-garden-love-plum",
    tag: [
      { id: 1, name: "plum" },
      { id: 2, name: "dry fruits" },
    ],
  }, 
  {
    id: 32,
    title: "Golden Garden Blueberry Plum",
    unit: "220g",
    description:
      "Dried fruit is fruit from which the majority of the original water content has been removed either naturally, through sun drying, or through the use of specialized dryers or dehydrators. ... Nearly half of the dried fruits sold are raisins, followed by dates, prunes, figs, apricots, peaches, apples, and pears.",
    price: 13,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4CF",
    stock: 110,
    images: [{id:1,small:images['product-44.png']},{id:2,medium:images['product-44-2x.png']}],
    category: "Dry Fruits",
    href: "golden-garden-blueberry-plum",
    tag: [
      { id: 1, name: "blueberry" },
      { id: 2, name: "dry fruits" },
    ],
  }, 
  {
    id: 33,
    title: "Dry Fig Loose",
    unit: "1kg",
    description:
      "Dried fruit is fruit from which the majority of the original water content has been removed either naturally, through sun drying, or through the use of specialized dryers or dehydrators. ... Nearly half of the dried fruits sold are raisins, followed by dates, prunes, figs, apricots, peaches, apples, and pears.",
    price: 11,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4CE",
    stock: 110,
    images: [{id:1,small:images['product-45.png']},{id:2,medium:images['product-45-2x.png']}],
    category: "Dry Fruits",
    href: "dry-fig-loose",
    tag: [
      { id: 1, name: "fig" },
      { id: 2, name: "dry fruits" },
    ],
  }, 
  {
    id: 34,
    title: "Dates Loose",
    unit: "1kg",
    description:
      "Dried fruit is fruit from which the majority of the original water content has been removed either naturally, through sun drying, or through the use of specialized dryers or dehydrators. ... Nearly half of the dried fruits sold are raisins, followed by dates, prunes, figs, apricots, peaches, apples, and pears.",
    price: 13,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4CD",
    stock: 110,
    images: [{id:1,small:images['product-46.png']},{id:2,medium:images['product-46-2x.png']}],
    category: "Dry Fruits",
    href: "dates-loose",
    tag: [
      { id: 1, name: "dates" },
      { id: 2, name: "dry fruits" },
    ],
  }, 
  {
    id: 35,
    title: "Dates Iranian Loose",
    unit: "1kg",
    description:
      "Dried fruit is fruit from which the majority of the original water content has been removed either naturally, through sun drying, or through the use of specialized dryers or dehydrators. ... Nearly half of the dried fruits sold are raisins, followed by dates, prunes, figs, apricots, peaches, apples, and pears.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4CC",
    stock: 110,
    images: [{id:1,small:images['product-47.png']},{id:2,medium:images['product-47-2x.png']}],
    category: "Dry Fruits",
    href: "dates-iranian-loose",
    tag: [
      { id: 1, name: "dates" },
      { id: 2, name: "dry fruits" },
    ],
  }, 
  
  //fresh-fruits
//////////////////////////  RESİMLER BOZULUYORRRR  !!!!!!!!!
  {
    id: 36,
    title: "Clementine",
    unit: "5ct",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 13,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4FC",
    stock: 110,
    images: [{id:1,small:images['product-.png']},{id:2,medium:images['product--2x.png']}],
    category: "Fresh Fruits",
    href: "clementine",
    tag: [
      { id: 1, name: "clementine" },
      { id: 2, name: "fresh fruits" },
    ],
  }, 
  {
    id: 37,
    title: "Blueberry",
    unit: "25qt",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F9",
    stock: 110,
    images: [{id:1,small:images['product-.png']},{id:2,medium:images['product--2x.png']}],
    category: "Fresh Fruits",
    href: "blueberry",
    tag: [
      { id: 1, name: "blueberries" },
      { id: 2, name: "fresh fruits" },
    ],
  }, 
  {
    id: 38,
    title: "Strawberrie",
    unit: "25oz",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 13,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F4",
    stock: 110,
    images: [{id:1,small:images['product-.png']},{id:2,medium:images['product--2x.png']}],
    category: "Fresh Fruits",
    href: "strawberrie",
    tag: [
      { id: 1, name: "strawberries" },
      { id: 2, name: "fresh fruits" },
    ],
  }, 
  {
    id: 39,
    title: "Strawberries Package",
    unit: "25oz",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 14,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4EF",
    stock: 110,
    images: [{id:1,small:images['product-.png']},{id:2,medium:images['product--2x.png']}],
    category: "Fresh Fruits",
    href: "strawberries-package",
    tag: [
      { id: 1, name: "strawberries" },
      { id: 2, name: "fresh fruits" },
    ],
  }, 
  {
    id: 40,
    title: "Pineapple Imported",
    unit: "5lb",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4ED",
    stock: 110,
    images: [{id:1,small:images['product-.png']},{id:2,medium:images['product--2x.png']}],
    category: "Fresh Fruits",
    href: "pineapple-imported",
    tag: [
      { id: 1, name: "pineapple" },
      { id: 2, name: "fresh fruits" },
    ],
  }, 
  {
    id: 41,
    title: "Haitian Mangoe",
    unit: "8ct",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 8,
    oldPrice: 10,
    sales: 20,
    sku: "9AF4D5",
    stock: 110,
    images: [{id:1,small:images['product-.png']},{id:2,medium:images['product--2x.png']}],
    category: "Fresh Fruits",
    href: "haitian-mangoe",
    tag: [
      { id: 1, name: "mango" },
      { id: 2, name: "fresh fruits" },
    ],
  }, 
  {
    id: 42,
    title: "Fresh Dates",
    unit: "10oz",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits",
    price: 14,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4D4",
    stock: 110,
    images: [{id:1,small:images['product-.png']},{id:2,medium:images['product--2x.png']}],
    category: "Fresh Fruits",
    href: "fresh-dates",
    tag: [
      { id: 1, name: "dates" },
      { id: 2, name: "fresh fruits" },
    ],
  }, 
  {
    id: 43,
    title: "Cranberries",
    unit: "9.5oz",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 13,
    oldPrice: 15,
    sales: 13,
    sku: "9AF4D3",
    stock: 110,
    images: [{id:1,small:images['product-.png']},{id:2,medium:images['product--2x.png']}],
    category: "Fresh Fruits",
    href: "cranberries",
    tag: [
      { id: 1, name: "cranberries" },
      { id: 2, name: "fresh fruits" },
    ],
  }, 
  {
    id: 44,
    title: "Mandarin Clementine",
    unit: "22lb",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits",
    price: 11,
    oldPrice: 12,
    sales: 8,
    sku: "9AF4D2",
    stock: 110,
    images: [{id:1,small:images['product-.png']},{id:2,medium:images['product--2x.png']}],
    category: "Fresh Fruits",
    href: "mandarin-clementine",
    tag: [
      { id: 1, name: "clementine" },
      { id: 2, name: "fresh fruits" },
    ],
  }, 
  {
    id: 45,
    title: "Avocado Juice Fruit",
    unit: "11lb",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 13,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4D1",
    stock: 110,
    images: [{id:1,small:images['product-.png']},{id:2,medium:images['product--2x.png']}],
    category: "Fresh Fruits",
    href: "avocado-juice-fruit",
    tag: [
      { id: 1, name: "avocado" },
      { id: 2, name: "fresh fruits" },
    ],
  }, 

  //fresh-vegetable
]





export const PopularProductData = [
  {
    id: 1,
    title: "Green Leaf Lettuce",
    unit: "each",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 14,
    oldPrice: 0,
    sales: 0,
    sku: "F001",
    stock: 6,
    images: [{id:1,small:images['product-1.png']},{id:2,medium:images['Green-Leaf-Lettuce-each-2x.png']}],
    category: "Fresh Vegetable",
    href: "green-leaf-lettuce",
    tag: [
      { id: 1, name: "lettuce" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 2,
    title: "Rainbow Chard",
    unit: "1lb",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4FD",
    stock: 0,
    images: [{id:1,small:images['product-2.png']},{id:2,medium:images['Rainbow-Chard-Package-per-lb-2x.png']}],
    category: "Fresh Vegetable",
    href:"rainbow-chard",
    tag: [
      { id: 1, name: "rainbow-chard" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 3,
    title: "Clementine",
    unit: "5ct",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 13,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4FC",
    stock: 0,
    images: [{id:1,small:images['product-3.png']},{id:2,medium:images['Clementine-5ct-2x.png']}],
    category: "Fresh Fruits",
    href:"clementine",
    tag: [
      { id: 1, name: "clementine" },
      { id: 2, name: "fresh fruits" },
    ],
  },
  {
    id: 4,
    title: "Rainbow Peppers",
    unit: "4ct",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4FA",
    stock: 52,
    images: [{id:1,small:images['product-4.png']},{id:2,medium:images['Rainbow-Peppers-4ct-2x.png']}],
    category: "Fresh Vegetable",
    href: "rainbow-peppers",
    tag: [
      { id: 1, name: "rainbow-peppers" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 5,
    title: "Blueberry",
    unit: "25qt",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 13,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F9",
    stock: 99,
    images: [{id:1,small:images['product-5.png']},{id:2,medium:images['Blackberries-1-25-qt-2x.png']}],
    category: "Fresh Fruits",
    href:"blueberry",
    tag: [
      { id: 1, name: "blueberries" },
      { id: 2, name: "fresh fruits" },
    ],
  },
  {
    id: 6,
    title: "Calabaza Squash",
    unit: "each",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F8",
    stock: 59,
    images: [{id:1,small:images['product-6.png']},{id:2,medium:images['Calabaza-Squash-Package-each-2x.png']}],
    category: "Fresh Vegetable",
    href: "calabazasquash",
    tag: [
      { id: 1, name: "calabaza-squash" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 7,
    title: "Lettuce",
    unit: "1lb",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 14,
    oldPrice: 0,
    sales: 0,
    sku: " 9AF4F7",
    stock: 103,
    images: [{id:1,small:images['product-7.png']},{id:2,medium:images['Lettuce-1lb-2x.png']}],
    category: "Fresh Vegetable",
    href: "lettuce",
    tag: [
      { id: 1, name: "lettuce" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 8,
    title: "Radicchio",
    unit: "12ct",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "F0056",
    stock: 0,
    images: [{id:1,small:images['product-8.png']},{id:2,medium:images['Radicchio-12ct-2x.png']}],
    category: "Fresh Vegetable",
    href: "radicchio",
    tag: [
      { id: 1, name: "radicchio" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 9,
    title: "Parsley",
    unit: "each",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F5",
    stock: 97,
    images: [{id:1,small:images['product-9.png']},{id:2,medium:images['Parsley-each-2x.png']}],
    category: "Fresh Vegetable",
    href: "parsley",
    tag: [
      { id: 1, name: "parsley" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 10,
    title: "Strawberrie",
    unit: "25oz",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 13,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F4",
    stock: 47,
    images: [{id:1,small:images['product-10.png']},{id:2,medium:images['Strawberries-9-25oz-2x.png']}],
    category: "Fresh Fruits",
    href: "strawberrie",
    tag: [
      { id: 1, name: "strawberries" },
      { id: 2, name: "fresh fruits" },
    ],
  },
  {
    id: 11,
    title: "Cauliflower",
    unit: "35lb",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F3",
    stock: 90,
    images: [{id:1,small:images['product-11.png']},{id:2,medium:images['Cauliflower-1-35lb-2x.png']}],
    category: "Fresh Vegetable",
    href: "cauliflower",
    tag: [
      { id: 1, name: "cauliflower" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 12,
    title: "Organic Purple Cauliflower",
    unit: "1lb",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 11,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F2",
    stock: 90,
    images: [{id:1,small:images['product-12.png']},{id:2,medium:images['Organic-Purple-Cauliflower-1lb-2x.png']}],
    category: "Fresh Vegetable",
    href: "organic-purple-cauliflower",
    
    tag: [
      { id: 1, name: "cauliflower" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 13,
    title: "Ahold Acorn Squash",
    unit: "1ct",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F1",
    stock: 0,
    images: [{id:1,small:images['product-13.png']},{id:2,medium:images['Ahold-Acorn-Squash-1ct-2x.png']}],
    category: "Fresh Vegetable",
    href: "ahold-acorn-squash",
    tag: [
      { id: 1, name: "squash" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 14,
    title: "Bok Choy Cabbage",
    unit: "1lb",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4F1",
    stock: 97,
    images: [{id:1,small:images['product-14.png']},{id:2,medium:images['Bok-Choy-Cabbage-per-lb-2x.png']}],
    category: "Fresh Vegetable",
    href: "bok-choy-cabbage",
    tag: [
      { id: 1, name: "cabbage" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 15,
    title: "Strawberries Package",
    unit: "25oz",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits.",
    price: 14,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4EF",
    stock: 86,
    images: [{id:1,small:images['product-15.png']},{id:2,medium:images['Strawberries-Package-2-25-oz-2x.png']}],
    category: " Fresh Fruits",
    href: "strawberries-hackage",
    tag: [
      { id: 1, name: "strawberries" },
      { id: 2, name: "fresh fruits" },
    ],
  },
  {
    id: 16,
    title: "Aloe Vera Leaf",
    unit: "each",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 15,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4EE",
    stock: 65,
    images: [{id:1,small:images['product-16.png']},{id:2,medium:images['Aloe-Vera-Leaf-each-2x.png']}],
    category: "Fresh Vegetable",
    href: "aloe-vera-leaf",
    tag: [
      { id: 1, name: "aloe-vera-leaf" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
  {
    id: 17,
    title: "Pineapple Imported",
    unit: "5lb",
    description:
      "In a botanical sense, a fruit is the fleshy or dry ripened ovary of a flowering plant, enclosing the seed or seeds. Apricots, bananas, and grapes, as well as bean pods, corn grains, tomatoes, cucumbers, and (in their shells) acorns and almonds, are all technically fruits",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4ED",
    stock: 70,
    images: [{id:1,small:images['product-17.png']},{id:2,medium:images['Pineapple-1-5lb-2x.png']}],
    category: "Fresh Fruits",
    href: "pineapple-imported",
    tag: [
      { id: 1, name: "pineapple" },
      { id: 2, name: "fresh fruits" },
    ],
  },
  {
    id: 18,
    title: "Organic Broccoli",
    unit: "10oz",
    description:
      "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
    price: 12,
    oldPrice: 0,
    sales: 0,
    sku: "9AF4EC",
    stock: 110,
    images: [{id:1,small:images['product-18.png']},{id:2,medium:images['Organic-Broccoli-10oz-2x.png']}],
    category: "Fresh Vegetable",
    href: "organic-broccoli",
    tag: [
      { id: 1, name: "broccoli" },
      { id: 2, name: "fresh vegetable" },
    ],
  },
];

export function getProductById(title){
  return PopularProductData.find((product)=>product.title.toLowerCase() === title.split("-").join(" "))
}

export function getProductByCategory(title){
  return PopularProductData.filter((product)=>product.category === title)
}